# ex02/Makefile
NAME        = PmergeMe
CXX         = c++
CXXFLAGS    = -Wall -Wextra -Werror -std=c++98 -g
SRC         = main.cpp PmergeMe.cpp
OBJ         = $(SRC:.cpp=.o)

all: $(NAME)

$(NAME): $(OBJ)
	$(CXX) $(CXXFLAGS) -o $@ $(OBJ)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f $(OBJ)

fclean: clean
	rm -f $(NAME)

re: fclean all
.PHONY: all clean fclean re
